# Generated by Django 2.2.7 on 2019-11-28 20:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyWritingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Hero Header', max_length=255)),
                ('hero_lead', wagtail.core.fields.RichTextField(help_text='Hero Lead Text', max_length=255)),
                ('hero_cta_text', models.CharField(help_text='Hero CTA Text', max_length=255)),
                ('hero_cta_url', models.URLField(help_text='Hero CTA Text', max_length=255)),
                ('testimonial', wagtail.core.fields.StreamField([('row', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
