# Generated by Django 2.2.6 on 2019-10-12 17:51

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtailmd.utils.MarkdownField(),
        ),
    ]
