# Generated by Django 2.2.6 on 2019-10-13 06:47

from django.db import migrations, models
import django.db.models.deletion
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0005_auto_20191012_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=wagtailmd.utils.MarkdownField(blank=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
